spring:
  application:
    name: server-local

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        init: jdbc:h2:./data/demo-local
  datasource:
    url: jdbc:h2:./data/demo-local
    driverClassName=: org.h2.Driver
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html